name: Docker Image CI

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build-and-push-Docker-image:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out code
    
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: saurabhkr952/dev-portfolio
          tags: ${{ github.sha }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}                     // Dockerhub password
          password: ${{ secrets.DOCKER_PASSWORD }}                     // Dockerhub username

  update-manifest:
    runs-on: ubuntu-latest 
    needs: ['build-and-push-Docker-image']
    steps:
      - uses: actions/checkout@v3
        with: 
          repository: saurabhkr952/dev-portfolio-manifest
          ref: 'main'
          token: ${{ secrets.G_TOKEN }}                               // github personal access token
      - name: setup git config
        run: |
          git config --global user.email "saurabhkr952@gmail.com"
          git config --global user.name "saurabhkr952"
          echo ${{ github.sha }}
          sed -i 's+saurabhkr952/dev-portfolio:.*+saurabhkr952/dev-portfolio:${{ github.sha }}+g' deployment.yaml
          git add -A
          git commit -m "Update image for - ${{ github.sha }}"
      - run: echo ${{ github }}
      - run: git push origin main
